FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core /app/core
COPY scripts /app/scripts
COPY sql /app/sql

CMD ["python", "-m", "core.agent_runner"]